### PR TITLE
Raise native image Xmx to 7g in GitHub workflows testing native mode as build-time RSS increased due to upstream changes

### PR DESCRIPTION
**Pull request by michalvavrik**
Same situation as here https://github.com/quarkus-qe/quarkus-test-suite/pull/2153, please check it out for context.

### CODE REVIEW

**Comment by rsvoboda** [comment]
pr.yaml has also `quarkus.native.native-image-xmx` defined for 003-quarkus-many-extensions

**Comment by michalvavrik** [comment]
> pr.yaml has also `quarkus.native.native-image-xmx` defined for 003-quarkus-many-extensions

Fixed, thank you.

**Comment by michalvavrik** [comment]
> https://github.com/quarkus-qe/beefy-scenarios/blob/main/.github/workflows/daily.yaml#L119 and https://github.com/quarkus-qe/beefy-scenarios/blob/main/.github/workflows/pr.yaml#L133 need to be bumped too

I thought there is dedicated Xmx exactly to avoid setting it everywhere. I'll raise it as it seems this logic is imperfect and CI fails.

**Comment by michalvavrik** [comment]
@rsvoboda CI is green.

**Review by rsvoboda — APPROVED** [review]

**Pull request merged**
