### PR TITLE
Added mysql and panache

### PR DESCRIPTION
**Pull request by Sgitario**
Added a module that test whether we can setup a REST API using ORM Panache and a multi-tenant data source configuration with Agroal extension and MySQL database.
These changes verify https://issues.redhat.com/browse/QUARKUS-549.

### CODE REVIEW

**Comment by Sgitario** [comment]
I verified that this is not working using 1.7.5.Final upstream version and working fine using 1.7.6.Final for jvm and native both.

**Comment by rsvoboda** [comment]
I miss highlight of the fact that XA is the important piece here.

Could you please rename the module to include `xa` ++ enhance README to include it too?

**Comment by Sgitario** [comment]
> I miss highlight of the fact that XA is the important piece here.
> 
> Could you please rename the module to include `xa` ++ enhance README to include it too?

Done, let me know if it looks better to you know.

**Review by rsvoboda — APPROVED** [review]
Thanks for the update, waiting for CI to finish.

**Pull request merged**
