### PR TITLE
Fix Spring Data compilation after Spring bump upstream

### PR DESCRIPTION
**Pull request by rsvoboda**
Fix Spring Data compilation after Spring bump upstream

After https://github.com/quarkusio/quarkus/pull/40344 compilation of this project fails.

### CODE REVIEW

**Review by michalvavrik — APPROVED** [review]
LGTM

CI fails over `Caused by: io.quarkus.runtime.configuration.ConfigurationException: Persistence unit 'fruits' was configured to run with a database version of at least '10.6.0', but the actual version is '10.3.0'. Consider upgrading your database. Alternatively, rebuild your application with 'quarkus.datasource."fruits".db-version=10.3.0' (but this may disable some features and/or impact performance negatively).` which is different issue

**Comment by rsvoboda** [comment]
I can look into 021-quarkus-panache-multiple-pus fail

**Comment by rsvoboda** [comment]
It's because of https://github.com/testcontainers/testcontainers-java/blob/main/modules/mariadb/src/main/java/org/testcontainers/containers/MariaDBContainer.java#L21

**Comment by michalvavrik** [comment]
thanks

**Pull request merged**
