### PR TITLE
Add a scenario with an extension registering many classes

### PR DESCRIPTION
**Pull request by essobedo**
A scenario to illustrate https://github.com/quarkusio/quarkus/issues/29693

### CODE REVIEW

**Comment by rsvoboda** [comment]
Thank you for the contribution. I will keep the PR as is till Quarkus issue gets resolved.

This test suite is kept in current form without new additions. For Qiuarkus 2 series we moved to https://github.com/quarkus-qe/quarkus-test-suite to unify for both bare metal and OpenShift scenarios.
This test suite is primarily used for daily runs against Quarkus main to detect significant changes done to the codebase.

**Comment by rsvoboda** [comment]
Your PR can land here, no issue with that. Tests from this repo are executed against Quarkus main.

If you plan to evolve the test coverage in the future, https://github.com/quarkus-qe/quarkus-test-suite is better place as more people are looking into that repo.

**Comment by rsvoboda** [comment]
@essobedo Quarkus PR is merged, so I tried to run the module against Quarkus main https://github.com/quarkusio/quarkus/commit/9666d205298ba4283c413bacdc494082d9cc5f77

Unfortunately I receive `Could not find artifact io.quarkus.qe:024-quarkus-extension-with-many-classes-to-register-deployment:jar:1.0.0-SNAPSHOT` when running `mvn -e clean verify -f 024-quarkus-extension-with-many-classes-to-register`

Is there a special way how to run the module?

**Comment by rsvoboda** [comment]
I was able to get around the above issue by disabling `generate-code` step (defined in root pom.xml) on deployment extension .
```diff
--- a/024-quarkus-extension-with-many-classes-to-register/deployment/pom.xml
+++ b/024-quarkus-extension-with-many-classes-to-register/deployment/pom.xml
@@ -8,6 +8,9 @@
         <relativePath>../pom.xml</relativePath>
     </parent>
     <artifactId>024-quarkus-extension-with-many-classes-to-register-deployment</artifactId>
+    <properties>
+        <quarkus.generate-code.skip>true</quarkus.generate-code.skip>
+    </properties>
     <dependencies>
         <dependency>
             <groupId>io.quarkus</groupId>
```

The build passes with Quarkus main.

But it also passes with 2.16.0.Final `mvn clean verify -f 024-quarkus-extension-with-many-classes-to-register -Dquarkus.platform.version=2.16.0.Final -Dquarkus-plugin.version=2.16.0.Final`
So the added scenario doesn't seem to be a full reproducer for https://github.com/quarkusio/quarkus/issues/29693 / https://github.com/quarkusio/quarkus/pull/29886

**Comment by essobedo** [comment]
Weird, let me ckeck

**Comment by essobedo** [comment]
@rsvoboda Your change is correct, I included it in my PR and added you as co-author.

Regarding your test, it is normal that it works because the bug only happen in native mode not in JVM mode, add `-Pnative` to your command and you should get a failure

**Comment by essobedo** [comment]
Hum I don't have the right email to add you as co-author

**Comment by rsvoboda** [comment]
`rsvoboda@redhat.com` is correct one. Tried native mode and it compiles with main, fails with 2.16

With main I just get many warnings like `Warning: Could not resolve io.quarkus.qe.SomeClass28655 for reflection configuration. Reason: java.lang.ClassNotFoundException: io.quarkus.qe.SomeClass28655.`. That's imho expected.

**Comment by essobedo** [comment]
@rsvoboda yes indeed, it’s the expected behavior.

**Comment by rsvoboda** [comment]
Will merge once CI finishes.

**Review by rsvoboda — APPROVED** [review]

**Pull request merged**
