### PR TITLE
Disable spring rest native tests due to Quarkus upstream issue

### PR DESCRIPTION
**Pull request by Sgitario**
Related Quarkus issue is https://github.com/quarkusio/quarkus/issues/15409

### CODE REVIEW

**Review by rsvoboda — CHANGES_REQUESTED** [review]
2 commits pls, one for adjustments, one for tests disabling

**Comment by Sgitario** [comment]
> 2 commits pls, one for adjustments, one for tests disabling

Done

**Comment by kshpak** [comment]
I would change commit messages to:
Adjustments to spring-data-rest module
Disable native tests in a spring-data-rest module

But it will trigger CI rerun :D It's up to you.
Apart from that LGTM

**Review by kshpak — APPROVED** [review]

**Comment by Sgitario** [comment]
> I would change commit messages to:
> Adjustments to spring-data-rest module
> Disable native tests in a spring-data-rest module
> 
> But it will trigger CI rerun :D It's up to you.
> Apart from that LGTM

Changed

**Comment by Sgitario** [comment]
Superseeded by https://github.com/quarkus-qe/beefy-scenarios/pull/121

**Pull request closed without merging**
