### PR TITLE
Add coverage to inject maps using the @ConfigProperty annotation

### PR DESCRIPTION
**Pull request by Sgitario**
This use case is now possible thanks to https://github.com/quarkusio/quarkus/issues/17269.

### CODE REVIEW

**Comment by Sgitario** [comment]
The failure is related to this issue: https://github.com/quarkusio/quarkus/issues/18814

**Comment by Sgitario** [comment]
The issue has been fixed in upstream. Rerunning.

**Comment by rsvoboda** [comment]
@Sgitario `Error:  Failed to execute goal net.revelc.code:impsort-maven-plugin:1.6.0:check (default) on project 014-quarkus-panache-with-transactions-xa: Imports are not sorted in /home/runner/work/beefy-scenarios/beefy-scenarios/014-quarkus-panache-with-transactions-xa/src/main/java/io/quarkus/qe/rest/data/UserRepository.java -> [Help 1]`

**Comment by Sgitario** [comment]
> @Sgitario `Error: Failed to execute goal net.revelc.code:impsort-maven-plugin:1.6.0:check (default) on project 014-quarkus-panache-with-transactions-xa: Imports are not sorted in /home/runner/work/beefy-scenarios/beefy-scenarios/014-quarkus-panache-with-transactions-xa/src/main/java/io/quarkus/qe/rest/data/UserRepository.java -> [Help 1]`

Yep, that was solved as part of https://github.com/quarkus-qe/beefy-scenarios/pull/242.
Rebasing.

**Review by rsvoboda — APPROVED** [review]

**Comment by pjgg** [comment]
LGTM

**Pull request merged**
