### PR TITLE
Disable Kamelet module

### PR DESCRIPTION
**Pull request by pjgg**
Quarkus Kamelet doesn't exist in Quarkus Kamelet 1.6

### CODE REVIEW

**Review by rsvoboda — COMMENTED** [review]
How do we ensure https://issues.redhat.com/browse/QUARKUS-1039 when this module gets diasbled?

**Review by Sgitario — CHANGES_REQUESTED** [review]
Please, amend also the version: https://github.com/quarkus-qe/beefy-scenarios/blob/752f18150b5c4da6ff2dfa4f0f79bf594a1f737e/pom.xml#L56.
It should be 1.6.0.

**Review by Sgitario — COMMENTED** [review]
This PR looks good to me now. 
However, as far I see, the above comment from @rsvoboda needs to be clarified/addressed before merging.

**Review by rsvoboda — APPROVED** [review]
Approving, QUARKUS-1039 can be checkd for code change presence, Pablo will also try to look at another approach without kamelet.

**Review by Sgitario — APPROVED** [review]

**Pull request merged**
