### PR TITLE
Fix 002 module in native

### PR DESCRIPTION
**Pull request by Sgitario**

### CODE REVIEW

**Comment by rsvoboda** [comment]
I tried to build it and tu it, but it ends with error:
```json
  "timestamp": "2021-03-04T17:56:49.569+01:00",
  "sequence": 874,
  "loggerClassName": "org.jboss.logging.Logger",
  "loggerName": "io.quarkus.runtime.Application",
  "level": "ERROR",
  "message": "Failed to start application (with profile prod)",
  "threadName": "main",
  "threadId": 1,
  "mdc": {},
  "ndc": "",
  "hostName": "rsvoboda-mac",
  "processName": "NativeImageGeneratorRunner$JDK9Plus",
  "processId": 9157,
  "exception": {
    "refId": 1,
    "exceptionType": "javax.enterprise.inject.UnsatisfiedResolutionException",
    "message": "No bean found for required type [class java.lang.Object] and qualifiers [[@io.quarkus.picocli.runtime.annotations.TopCommand()]]",
    "frames": [
...
```

```
mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/rsvoboda/.sdkman/candidates/maven/current
Java version: 11.0.10, vendor: GraalVM Community, runtime: /Users/rsvoboda/.sdkman/candidates/java/21.0.0.2.r11-grl
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```

command I used:
```
mvn clean install -Dnative \
  -Dquarkus.native.additional-build-args=--allow-incomplete-classpath \
  -pl 002-quarkus-all-extensions -Phigh-memory-needed
```

Commenting out picocli helped a bit, no error in the log, but start doesn't finish with expected "started" message.

**Comment by Sgitario** [comment]
> I tried to build it and tu it, but it ends with error:
> 
> ```json
>   "timestamp": "2021-03-04T17:56:49.569+01:00",
>   "sequence": 874,
>   "loggerClassName": "org.jboss.logging.Logger",
>   "loggerName": "io.quarkus.runtime.Application",
>   "level": "ERROR",
>   "message": "Failed to start application (with profile prod)",
>   "threadName": "main",
>   "threadId": 1,
>   "mdc": {},
>   "ndc": "",
>   "hostName": "rsvoboda-mac",
>   "processName": "NativeImageGeneratorRunner$JDK9Plus",
>   "processId": 9157,
>   "exception": {
>     "refId": 1,
>     "exceptionType": "javax.enterprise.inject.UnsatisfiedResolutionException",
>     "message": "No bean found for required type [class java.lang.Object] and qualifiers [[@io.quarkus.picocli.runtime.annotations.TopCommand()]]",
>     "frames": [
> ...
> ```
> 
> ```
> mvn -version
> Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
> Maven home: /Users/rsvoboda/.sdkman/candidates/maven/current
> Java version: 11.0.10, vendor: GraalVM Community, runtime: /Users/rsvoboda/.sdkman/candidates/java/21.0.0.2.r11-grl
> Default locale: en_GB, platform encoding: UTF-8
> OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
> ```
> 
> command I used:
> 
> ```
> mvn clean install -Dnative \
>   -Dquarkus.native.additional-build-args=--allow-incomplete-classpath \
>   -pl 002-quarkus-all-extensions -Phigh-memory-needed
> ```
> 
> Commenting out picocli helped a bit, no error in the log, but start doesn't finish with expected "started" message.

Adjusted the PR to make the module build into Native and:
- Removed Picocli extension as it's incompatible with REST
- Added PostgresSQL and MongoDB resources necessary for some Quarkus extensions.

Still the native test is not working, so I've disabled it for now.

**Comment by rsvoboda** [comment]
Native build fails for me, using GraalVM 21.0.0.2.
@Sgitario were you succesfull with building the app?

```
[002-quarkus-all-extensions-1.0.0-SNAPSHOT-runner:54263]        setup:   9,890.29 ms,  5.25 GB
15:18:14,417 INFO  [org.hib.Version] HHH000412: Hibernate ORM core version 5.4.29.Final
15:18:14,427 INFO  [org.hib.env.boo.int.EnversServiceImpl] Envers integration enabled? : true
15:18:14,447 INFO  [org.hib.ann.com.Version] HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
15:18:14,521 INFO  [org.hib.dia.Dialect] HHH000400: Using dialect: io.quarkus.hibernate.orm.runtime.dialect.QuarkusPostgreSQL10Dialect
15:18:14,747 INFO  [org.hib.val.int.uti.Version] HV000001: Hibernate Validator 6.2.0.Final
15:18:15,789 WARNING [org.apa.tik.par.PDFParser] J2KImageReader not loaded. JPEG2000 files will not be processed.
See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
for optional dependencies.

15:18:16,127 WARN  [io.sma.graphql] SRGQL010000: Schema is null, or it has no operations. Not bootstrapping SmallRye GraphQL
15:19:45,529 INFO  [org.inf.SECURITY] ISPN000947: Using Java SSL Provider
15:19:47,447 INFO  [org.jbo.threads] JBoss Threads version 3.2.0.Final
ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.8ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.8
[002-quarkus-all-extensions-1.0.0-SNAPSHOT-runner:54263]     (clinit):   4,129.29 ms,  6.99 GB
[002-quarkus-all-extensions-1.0.0-SNAPSHOT-runner:54263]   (typeflow): 128,292.53 ms,  6.99 GB
[002-quarkus-all-extensions-1.0.0-SNAPSHOT-runner:54263]    (objects): 149,565.70 ms,  6.99 GB
[002-quarkus-all-extensions-1.0.0-SNAPSHOT-runner:54263]   (features):   9,350.80 ms,  6.99 GB
[002-quarkus-all-extensions-1.0.0-SNAPSHOT-runner:54263]     analysis: 308,768.03 ms,  6.99 GB
Error: Unsupported features in 2 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: graphql.GraphQL$Builder.defaultDataFetcherExceptionHandler(graphql.execution.DataFetcherExceptionHandler). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace:
	at parsing io.smallrye.graphql.execution.ExecutionService.getGraphQL(ExecutionService.java:222)
Call path from entry point to io.smallrye.graphql.execution.ExecutionService.getGraphQL():
	at io.smallrye.graphql.execution.ExecutionService.getGraphQL(ExecutionService.java:215)
	at io.smallrye.graphql.execution.ExecutionService.execute(ExecutionService.java:99)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doRequest(SmallRyeGraphQLExecutionHandler.java:176)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handleGet(SmallRyeGraphQLExecutionHandler.java:133)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doHandle(SmallRyeGraphQLExecutionHandler.java:96)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handle(SmallRyeGraphQLExecutionHandler.java:64)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handle(SmallRyeGraphQLExecutionHandler.java:37)
	at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.lambda$pollRecords$6(KafkaReadStreamImpl.java:158)
	at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl$$Lambda$2754/0x00000007c7b2c440.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: graphql.execution.ExecutionStepInfo.getPath(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace:
	at parsing io.smallrye.graphql.execution.context.SmallRyeContext.getPath(SmallRyeContext.java:119)
Call path from entry point to io.smallrye.graphql.execution.context.SmallRyeContext.getPath():
	at io.smallrye.graphql.execution.context.SmallRyeContext.getPath(SmallRyeContext.java:118)
	at io.smallrye.graphql.execution.context.SmallRyeContext.toString(SmallRyeContext.java:317)
	at java.lang.String.valueOf(String.java:2951)
	at java.io.PrintStream.print(PrintStream.java:745)
	at java.io.PrintStream.println(PrintStream.java:882)
	at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:757)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)

com.oracle.svm.core.util.UserError$UserException: Unsupported features in 2 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: graphql.GraphQL$Builder.defaultDataFetcherExceptionHandler(graphql.execution.DataFetcherExceptionHandler). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace:
	at parsing io.smallrye.graphql.execution.ExecutionService.getGraphQL(ExecutionService.java:222)
Call path from entry point to io.smallrye.graphql.execution.ExecutionService.getGraphQL():
	at io.smallrye.graphql.execution.ExecutionService.getGraphQL(ExecutionService.java:215)
	at io.smallrye.graphql.execution.ExecutionService.execute(ExecutionService.java:99)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doRequest(SmallRyeGraphQLExecutionHandler.java:176)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handleGet(SmallRyeGraphQLExecutionHandler.java:133)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doHandle(SmallRyeGraphQLExecutionHandler.java:96)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handle(SmallRyeGraphQLExecutionHandler.java:64)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handle(SmallRyeGraphQLExecutionHandler.java:37)
	at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.lambda$pollRecords$6(KafkaReadStreamImpl.java:158)
	at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl$$Lambda$2754/0x00000007c7b2c440.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: graphql.execution.ExecutionStepInfo.getPath(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace:
	at parsing io.smallrye.graphql.execution.context.SmallRyeContext.getPath(SmallRyeContext.java:119)
Call path from entry point to io.smallrye.graphql.execution.context.SmallRyeContext.getPath():
	at io.smallrye.graphql.execution.context.SmallRyeContext.getPath(SmallRyeContext.java:118)
	at io.smallrye.graphql.execution.context.SmallRyeContext.toString(SmallRyeContext.java:317)
	at java.lang.String.valueOf(String.java:2951)
	at java.io.PrintStream.print(PrintStream.java:745)
	at java.io.PrintStream.println(PrintStream.java:882)
	at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:757)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)

	at com.oracle.svm.core.util.UserError.abort(UserError.java:82)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:233)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:773)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:563)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported features in 2 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: graphql.GraphQL$Builder.defaultDataFetcherExceptionHandler(graphql.execution.DataFetcherExceptionHandler). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace:
	at parsing io.smallrye.graphql.execution.ExecutionService.getGraphQL(ExecutionService.java:222)
Call path from entry point to io.smallrye.graphql.execution.ExecutionService.getGraphQL():
	at io.smallrye.graphql.execution.ExecutionService.getGraphQL(ExecutionService.java:215)
	at io.smallrye.graphql.execution.ExecutionService.execute(ExecutionService.java:99)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doRequest(SmallRyeGraphQLExecutionHandler.java:176)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handleGet(SmallRyeGraphQLExecutionHandler.java:133)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doHandle(SmallRyeGraphQLExecutionHandler.java:96)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handle(SmallRyeGraphQLExecutionHandler.java:64)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handle(SmallRyeGraphQLExecutionHandler.java:37)
	at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.lambda$pollRecords$6(KafkaReadStreamImpl.java:158)
	at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl$$Lambda$2754/0x00000007c7b2c440.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: graphql.execution.ExecutionStepInfo.getPath(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace:
	at parsing io.smallrye.graphql.execution.context.SmallRyeContext.getPath(SmallRyeContext.java:119)
Call path from entry point to io.smallrye.graphql.execution.context.SmallRyeContext.getPath():
	at io.smallrye.graphql.execution.context.SmallRyeContext.getPath(SmallRyeContext.java:118)
	at io.smallrye.graphql.execution.context.SmallRyeContext.toString(SmallRyeContext.java:317)
	at java.lang.String.valueOf(String.java:2951)
	at java.io.PrintStream.print(PrintStream.java:745)
	at java.io.PrintStream.println(PrintStream.java:882)
	at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:757)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)

	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:129)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:770)
	... 8 more
```

**Comment by rsvoboda** [comment]
```
[002-quarkus-all-extensions-1.0.0-SNAPSHOT-runner:56172]     (clinit):   4,281.80 ms,  7.05 GB
[002-quarkus-all-extensions-1.0.0-SNAPSHOT-runner:56172]   (typeflow): 130,930.46 ms,  7.05 GB
[002-quarkus-all-extensions-1.0.0-SNAPSHOT-runner:56172]    (objects): 139,824.90 ms,  7.05 GB
[002-quarkus-all-extensions-1.0.0-SNAPSHOT-runner:56172]   (features):   8,765.05 ms,  7.05 GB
[002-quarkus-all-extensions-1.0.0-SNAPSHOT-runner:56172]     analysis: 297,637.83 ms,  7.05 GB
[002-quarkus-all-extensions-1.0.0-SNAPSHOT-runner:56172]     universe:   9,129.36 ms,  7.15 GB
[002-quarkus-all-extensions-1.0.0-SNAPSHOT-runner:56172]      (parse):  43,347.87 ms,  8.67 GB
[002-quarkus-all-extensions-1.0.0-SNAPSHOT-runner:56172]     (inline):  26,706.68 ms, 10.84 GB
[002-quarkus-all-extensions-1.0.0-SNAPSHOT-runner:56172]    (compile):  77,863.30 ms, 11.21 GB
[002-quarkus-all-extensions-1.0.0-SNAPSHOT-runner:56172]      compile: 159,212.71 ms, 11.10 GB
[002-quarkus-all-extensions-1.0.0-SNAPSHOT-runner:56172]        image:  37,947.86 ms,  9.90 GB
[002-quarkus-all-extensions-1.0.0-SNAPSHOT-runner:56172]        write:   4,760.64 ms,  9.90 GB
[002-quarkus-all-extensions-1.0.0-SNAPSHOT-runner:56172]      [total]: 543,932.01 ms,  9.90 GB
```

with `mvn clean install -Dnative  -Dquarkus.native.additional-build-args=--allow-incomplete-classpath`

Please add `quarkus.native.additional-build-args=--allow-incomplete-classpath` into application.properties and we will be good to merge

**Comment by Sgitario** [comment]
> quarkus.native.additional-build-args=--allow-incomplete-classpath

Updated. I've tried it and it looks good now. Thanks for the tip!

**Review by rsvoboda — APPROVED** [review]

**Pull request merged**
