### PR TITLE
Separate @QuarkusTest execution

### PR DESCRIPTION
**Pull request by gsmet**
At some point, maybe this should be put in a shared constant but it
seems a bit too involved to create a shared module just for that.

### CODE REVIEW

**Comment by gsmet** [comment]
This should make CI green again \o/

**Comment by rsvoboda** [comment]
@gsmet why does `QuarkusProdModeTest` need separate surefire execution?

**Comment by gsmet** [comment]
Because you cannot mix them with the regular unit tests. It has always been like that and was enforced at some point but the check was removed somehow.

It got reintroduced here: https://github.com/quarkusio/quarkus/pull/19329 and this comment from Stuart: https://github.com/quarkusio/quarkus/issues/19325#issuecomment-896378222 .

**Comment by rsvoboda** [comment]
Thanks for details!

**Review by Sgitario — APPROVED** [review]

**Review by rsvoboda — APPROVED** [review]

**Comment by gsmet** [comment]
Now that I think of it a bit more, I think we need to isolate the `@QuarkusTest` not the prod mode as this is the one conflicting.

I'll change the PR and push a PR on core to add a `@Tag` for `@QuarkusTest`.

**Comment by gsmet** [comment]
I adjusted the PR and created https://github.com/quarkusio/quarkus/pull/19477 so that at some point we don't have to tag the tests anymore.

**Pull request merged**
