### PR TITLE
[1.11] kafka gracefull shutdown

### PR DESCRIPTION
**Pull request by pjgg**
depends on: #159 

- Refactor `KafkaGratefulShutdownTest` in order to make it works on branch 1.11

### CODE REVIEW

**Review by Sgitario — APPROVED** [review]

**Comment by Sgitario** [comment]
@pjgg please, rebase this PR.

**Comment by Sgitario** [comment]
@pjgg the branch 1.11 has been updated to use 1.11.7.Final, so this PR should be passing now. Please, rebase and let's confirm it.

**Comment by Sgitario** [comment]
@pjgg did you rebase this PR? I see that it's still not passing

**Comment by pjgg** [comment]
Finally, this amendment is not going to be backported to 1.11.7

**Pull request closed without merging**
