### PR TITLE
Quarkus - KafkaClient coverage

### PR DESCRIPTION
**Pull request by pjgg**
- Uncomment module `009-quarkus-infinispan-grpc-kafka` from main pom
- Add quarkus Apache Kafka client coverage
-  package `io.quarkus.qe.grateful.shutdown` was renamed to `io.quarkus.qe.kafka` in order to group all Kafka test together 
- GrpcService annotation was renamed to GrpcClient following Quarkus2.x migration guides

### CODE REVIEW

**Review by Sgitario — CHANGES_REQUESTED** [review]
I think this PR mixes up several topics. Can you provide a different PR for each and more details about each one? For example:
- The 009 was disabled because some issues on upstream. Was this issue fixed or did you workaround somehow? As far I can see, the issue remains open: https://github.com/quarkusio/quarkus/issues/16386
- The package "io.quarkus.qe.grateful.shutdown" was renamed to "io.quarkus.qe.kafka", but I miss the motivation of this change.
- There are some format changes which are unexpected as far I know. If these changes were automatically done by your IDE settings, these should be addressed into a separated PR to ammend the format settings in the repo. 
- The GrpcService renaming

**Comment by rsvoboda** [comment]
> different PR for each and more details about each one

I don't think it's really needed, imho split into more commits as part of this PR would work just fine

**Comment by Sgitario** [comment]
> > different PR for each and more details about each one
> 
> I don't think it's really needed, imho split into more commits as part of this PR would work just fine

From my point of view, this PR enables the module 009 that supposed to be failing, that's why I would need further investigation whether the issue is fixed in upstream or adding the kafka-client dependency is a workaround... 
Having all the changes in the same PR disallow us to see what made the module to be fixed.

**Comment by pjgg** [comment]
The PR was re-submitted in order to split all the changes in three commits:
1. Apache Kafka Client commit
2. Grpc package name refactor (Quarkus 2.x)
3. Uncomment project module 009 after re-check a related issue.

**Review by Sgitario — APPROVED** [review]

**Pull request merged**
