### PR TITLE
Jbang - cryptocurrency scenario

### PR DESCRIPTION
**Pull request by pjgg**
## Jbang scenario:
- Reactive routes
- Mutiny
- Swagger
- Junit

### CODE REVIEW

**Comment by rsvoboda** [comment]
I received 
```
[INFO] Running io.quarkus.qe.jbang.QuarkusRestTest
[ERROR] Tests run: 3, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 64.36 s <<< FAILURE! - in io.quarkus.qe.jbang.QuarkusRestTest
[ERROR] getCurrency  Time elapsed: 4.118 s  <<< FAILURE!
java.lang.AssertionError:
1 expectation failed.
Expected status code <200> but was <500>.

	at io.quarkus.qe.jbang.QuarkusRestTest.getCurrency(QuarkusRestTest.java:88)

[ERROR] getAllCurrencies  Time elapsed: 0.096 s  <<< FAILURE!
java.lang.AssertionError:
1 expectation failed.
Expected status code <200> but was <500>.

	at io.quarkus.qe.jbang.QuarkusRestTest.getAllCurrencies(QuarkusRestTest.java:72)

```
when running 
```
mvn verify -Dnative -pl 016-quarkus-jbang
```

How can I get better info what went wrong?

**Comment by rsvoboda** [comment]
`curl -v http://localhost:9090/api/stock/currency/DRACO/value` gives following error when running just jbang

```
RS:jbang rsvoboda$ jbang stockCryptoCurrency.java
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2021-02-11 15:50:17,443 INFO  [io.quarkus] (main) Quarkus 1.11.0.Final on JVM started in 0.810s. Listening on: http://0.0.0.0:9090
2021-02-11 15:50:17,455 INFO  [io.quarkus] (main) Profile prod activated. 
2021-02-11 15:50:17,455 INFO  [io.quarkus] (main) Installed features: [cdi, mutiny, resteasy-mutiny, smallrye-context-propagation, smallrye-openapi, swagger-ui, vertx, vertx-web]
2021-02-11 15:50:24,286 INFO  [io.qua.qe.jba.stockCryptoCurrency] (vert.x-eventloop-thread-11) The application is starting with profile prod
2021-02-11 15:50:25,315 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-11) HTTP Request to /api/stock/currency/DRACO/value failed, error id: 898d463a-550e-4f81-873b-5e93dc76675a-1: java.lang.NullPointerException
        at io.quarkus.qe.jbang.stockCryptoCurrency$CryptoCurrencyValues.from(stockCryptoCurrency.java:157)
        at io.quarkus.qe.jbang.stockCryptoCurrency$CryptoCurrencyValues.lambda$getCurrencyValue$1(stockCryptoCurrency.java:168)
        at io.smallrye.mutiny.operators.UniOnItemTransform$1.onItem(UniOnItemTransform.java:26)
        at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:31)
        at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
        at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:31)
        at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:86)
        at io.smallrye.mutiny.vertx.AsyncResultUni.lambda$subscribing$1(AsyncResultUni.java:34)
        at io.vertx.mutiny.ext.web.client.HttpRequest$9.handle(HttpRequest.java:617)
        at io.vertx.mutiny.ext.web.client.HttpRequest$9.handle(HttpRequest.java:614)
        at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:313)
        at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:300)
        at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:275)
        at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:70)
        at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:32)
        at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:272)
        at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:282)
        at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:243)
        at io.vertx.ext.web.client.impl.HttpContext.lambda$null$2(HttpContext.java:373)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by rsvoboda** [comment]
Accessing https://min-api.cryptocompare.com/ gives me error response with "You are over your rate limit please upgrade your account!" message

**Comment by rsvoboda** [comment]
about the test fails ... `static final String WIREMOCK_HOST = "172.17.0.1"; // Docker to host` looks suspicious, I'm on macOS btw

**Comment by rsvoboda** [comment]
@pjgg I'm not sure if this is good to have this JBang module in BeefyTS

 - works only on Linux (we need to consider Windows and macOS)
 - the script relies on external service which has rate limits, makes it harder to update the script / run it locally
   -  I know test is using mock and jbang-action image, but it has some drawbacks too
 - we can't control BOM version used in the script (would like to use RHBQ bits eventually)

So at this stage I hesitate to have something like this in the repo, especially when we have no product requirement on JBang integration.

If we proceed with JBang and Quarkus/RHBQ closer testing we should probably have dedicated TS with some tooling around to orchestrate some testing details ... e.g. be able to overide BOM version, running directly jbang command (and support to install it, upgrade to latest). Running in container can be a way, but it can be troublesome for Windows and macOS where docker runs in VM.

**Comment by maxandersen** [comment]
FYI, you can override the bom. Jbang support using properties in the //DEPS lines.

**Pull request closed without merging**
